# documentación en: 
# si se puede!!
# https://docs.github.com/es/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
# https://github.com/marketplace/actions/telegram-message-notify
# https://github.com/appleboy/telegram-action/blob/master/entrypoint.sh
# telegram to es el id del chat, grupo o persona y token el token
# obtener info del bot https://api.telegram.org/bot1429561926:AAFdgaL1XTorvyBGp2EAQVEkJHi1BN6Uc10/getUpdates
name: bot telegram
on: 
  push:
    branches:
      - main
      - master
      - develop
      - feature/login
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: envio de mensaje
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        # args: The ${{ github.event_name }} event triggered first step.
        # message: ${{github.sha}} => Hola, el usuario ${{ github.actor }} ha ejecutado una acción, en el repositorio ${{github.repository}} generando un ${{ github.event_name }} es el commit ${{github.run_number}}
        message:  => En ${{github.repository}}, ${{ github.actor }} ha realizado "${{ github.event.commits[0].message }}", generando un ${{ github.event_name }} es el commit ${{github.run_number}}
